appName: myapp

port: 80

image:
  name: afzal442/movie-catalogue
  tag: v4

replicas: 3

serviceAccount:
  name: myapp-sa

role:
  name: myapp-role

roleBinding:
  name: myapp-rolebinding

resources:
  requests:
    memory: 0.5Gi
    cpu: 250m
