appName: myapp

port: 80

image:
  name: gcr.io/heptio-images/ks-guestbook-demo
  tag: 0.1

replicas: 2

serviceAccount:
  name: myapp-sa

role:
  name: myapp-role

roleBinding:
  name: myapp-rolebinding

resources:
  requests:
    memory: 0.5Gi
    cpu: 250m

env:  # Add env variables here
  OPENCOST_PARQUET_FILE_KEY_PREFIX: "dev"
