apiVersion: v1
kind: Namespace
metadata:
  name: argocd-2
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-saas-e2e-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-proj:test1
spec:
  project: default
  source:
    repoURL: https://github.com/akuityio/kargo-saas-e2e-test.git
    targetRevision: HEAD
    path: stages/test
  destination:
    server: http://cluster-test-1:8001
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-saas-e2e-test-2
  namespace: argocd-2
  annotations:
    kargo.akuity.io/authorized-stage: kargo-proj:test1
spec:
  project: default-2
  source:
    repoURL: https://github.com/akuityio/kargo-saas-e2e-test.git
    targetRevision: HEAD
    path: stages/prod
  destination:
    server: http://cluster-test-1:8001
    namespace: argocd2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    