apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: minikube
            name: frontend
            namespace: mydev
            repoPath: appSet/dev
            labels:
              app-group: frontend-team
          - cluster: minikube
            name: backend
            namespace: mydev
            repoPath: appSet/prod
            labels:
              app-group: backend-team
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app-group
              operator: In
              values:
                - frontend-team
        - matchExpressions:
            - key: app-group
              operator: In
              values:
                - backend-team
          maxUpdate: 10%
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cloud-hacks/argocd-io
        targetRevision: HEAD
        path: '{{repoPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
