apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            name: mydevapp
            repoPath: appSet/dev
            label: mydev-team
          - cluster: prod
            name: myprodapp
            repoPath: appSet/prod
            label: myprod-team
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - mydev-team
        - matchExpressions:
            - key: app
              operator: In
              values:
                - myprod-team
          maxUpdate: 20% # all applications matched are updated 10% at a time
  template:
    metadata:
      name: '{{name}}'
      labels:
        app: '{{label}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cloud-hacks/argocd-io
        targetRevision: HEAD
        path: '{{repoPath}}'
      destination:
        server: in-cluster
        namespace: mydev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
