apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: minikube
            name: mydevapp
            repoPath: appSet/dev
            labels:
              app-group: mydev-team
          - cluster: minikube
            name: myprodapp
            repoPath: appSet/prod
            labels:
              app-group: myprod-team
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app-group
              operator: In
              values:
                - mydev-team
        - matchExpressions:
            - key: app-group
              operator: In
              values:
                - myprod-team
          maxUpdate: 50% # all applications matched are updated 10% at a time
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cloud-hacks/argocd-io
        targetRevision: HEAD
        path: '{{repoPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: mydev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
