apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev-mini
            name: dev
            repoPath: guestbook
            label: mydev-team
          - cluster: prod-mini
            name: prod
            repoPath: guestbook
            label: myprod-team
          - cluster: staging-mini
            name: staging
            repoPath: guestbook
            label: mystaging-team
  template:
    metadata:
      name: '{{name}}'
      labels:
        app: '{{label}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/cloud-hacks/argocd-io
        targetRevision: HEAD
        path: '{{repoPath}}'
        helm:
          valueFiles:
            - values-{{name}}.yaml
      destination:
        name: '{{name}}'
        namespace: mydev
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true