apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: ecom-microservice
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Microservices for my project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/cloud-hacks/argocd-io
  # Only permit applications to deploy to the mydev namespace in the same cluster
  destinations:
  - namespace: mydevapp
    name: dev
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Deny all namespaced-scoped resources from being created, except for Deployment and others
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: ''
    kind: Pod
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: 'apps'
    kind: ReplicaSet
  - group: ''
    kind: Endpoints
  - group: 'batch'
    kind: Job
  - group: ''
    kind: ServiceAccount
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to ecom-microservice
    policies:
    - p, proj:ecom-microservice:read-only, applications, get, ecom-microservice/*, allow
    groups:
    - app-team
