apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.pagerdutyv2: "P7N57QR"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    name: {{ .Values.spec.destination.name }}
  project: ecom-microservice
  source:
    path: kustom-webapp/overlays/dev
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}