apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: ecom-microservice
  source:
    path: helm-webapp
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}