apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    name: {{ .Values.spec.destination.name }}
  project: ecom-microservice
  source:
    path: helm-webapp
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true