apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevapp-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mydevapp-ui
  template:
    metadata:
      labels:
        app: mydevapp-ui
    spec:
      containers:
      - image: gcr.io/google-samples/gb-frontend:v5
        name: mydevapp-ui
        ports:
        - containerPort: 80