apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-guestbook-01
  namespace: team-dev-ux
spec:
  destination:
    namespace: any-guestbook
    name: test
  project: app-in-any-ns
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-in-any-ns
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - team-dev-ui
  sourceRepos:
  - '*'
# ---