apiVersion: v1
kind: Namespace
metadata:
  name: team-dev-ui
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-guestbook-01
  namespace: cams
  annotations:
    # notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: tempnobs@gmail.com
    argocd.argoproj.io/manifest-generate-paths: .;../shared
spec:
  destination:
    namespace: any-guestbook
    name: test
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - external-secrets
  project: cams
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        cluster-artifactory-creds: cluster-external-secret
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: app-in-any-ns
#   namespace: argocd
# spec:
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   destinations:
#   - namespace: '*'
#     server: '*'
#   sourceNamespaces:
#   - team-dev-ui
#   sourceRepos:
#   - '*'
# ---