apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-in-any-ns
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - /^((?!kube-system).)*$/
  sourceRepos:
  - '*'