apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapprod-test
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.argocd-notifications-afzal442: ""
    notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: afzal442@gmail.com
    notifications.argoproj.io/subscribe.appProgressingTooLong.akuity-email-sp: tempnobs@gmail.com
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: prod
    namespace: gb-top
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true