apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapprod-test
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.argocd-akuity-alert: ""
    # notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: afvn.in@gmail.com
    # notifications.argoproj.io/subscribe.appProgressingTooLong.akuity-email-sp: tempnobs@gmail.com
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    name: test
    namespace: gb-top
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true