apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapprod-test-ak17
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    # notifications.argoproj.io/subscribe.appProgressingTooLong.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    path: helm-guestbook
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: http://cluster-prod:8001
    namespace: gb-top
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true