apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapprod-test
  # annotations:
  #   notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: http://cluster-prod:8001
    namespace: gb-test
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true