apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapprod-test
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.myakuity-alert: ""
    notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: afzal.ansari@akuity.io
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: http://cluster-prod:8001
    namespace: gb-top
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true