apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-test
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed.argocd-akuity-alert: ""
    # notifications.argoproj.io/subscribe.on-sync-status-change.smee: ""
    # notifications.argoproj.io/subscribe.on-deployment-ready.awssqs: "awssqs"
    notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: afvn.in@gmail.com
    # notifications.argoproj.io/subscribe.appProgressingTooLong.akuity-email-sp: tempnobs@gmail.com
spec:
  project: default-3
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    path: helm-guestbook
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: test
    namespace: gb-test
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true