apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstraper-test
  namespace: app-in-any-ns
  # annotations:
      # notifications.argoproj.io/subscribe.on-app-sync-succeeded.akuity-email-sp: tempnobs@gmail.com
  #   notifications.argoproj.io/subscribe.on-deployed.github: ""
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  # namespace: dev Without default ns, app of apps won't be created
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: app-in-any-ns
  source:
    path: app-configs/appofanyapps
    repoURL: https://github.com/cloud-hacks/argocd-io
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true