apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstraper
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  # namespace: dev Without default ns, app of apps won't be created
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: apps
    repoURL: https://github.com/cloud-hacks/argocd-io
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true