apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    targetRevision: main
    # ref: values
    path: helm-webapp
    helm:
      valueFiles:
      - values-dev.yaml
      # ignoreMissingValueFiles: true
  destination:
    name: dev
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    # - RespectIgnoreDifferences=true
    - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
