apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapp
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    targetRevision: main
    # ref: values
    path: helm-webapp
    helm:
      valueFiles:
      - values-dev.yaml
      parameters:
      - name: securityContext
        value: null
      # - name: env
      #   value: '[{"name":"OPENCOST_PARQUET_FILE_KEY_PREFIX","value":"test"}]'
      # ignoreMissingValueFiles: true
  destination:
    name: dev
    namespace: staging
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
    # - RespectIgnoreDifferences=true
    - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
