apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: app-in-any-ns
spec:
  destination:
    namespace: any-guestbook
    name: prod
  project: app-in-any-namespace
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-in-any-namespace
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - /^((?!kube-system).)*$/
  sourceRepos:
  - '*'
---
# It's also important to note that proper RBAC should be configured to properly view the apps in the UI/CLI.  Please see: https://argo-cd.readthedocs.io/en/latest/operator-manual/app-any-namespace/#application-rbac