apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-microservice
  namespace: mydev
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    targetRevision: HEAD
    path: appProject
  destination:
    server: in-cluster
    namespace: mydevapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true