apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprodapp-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myprodapp-ui
  template:
    metadata:
      labels:
        app: myprodapp-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: myprodapp-ui
        ports:
        - containerPort: 80