apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mprodapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-hacks/argocd-io.git
    targetRevision: HEAD
    path: helm-webapp
  destination:
    server: https://192.168.49.2:8443
    namespace: mydev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true