apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleepy
  template:
    metadata:
      labels:
        app: sleepy
    spec:
      containers:
      - name: sleepy-container
        image: busybox
        command: ["sh", "-c", "sleep 3600"]  # simulate a long-running container
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              if [ "$(($(date +%s) - $(stat -c %Y /tmp/ready)))" -gt 120 ]; then
                exit 0
              else
                exit 1
              fi
          initialDelaySeconds: 0
          periodSeconds: 5
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - "date +%s > /tmp/ready"
        # args: ["sh", "-c", "date +%s > /tmp/ready"]