apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: dev-mini
            name: test
            stage: dev
          # - stage: uat
          # - cluster: prod-mini
          #   name: prod
          #   stage: prod
  template:
    metadata:
      name: kargo-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/afzal442/kargo-demo
        targetRevision: HEAD
        path: .
      destination:
        name: '{{name}}'
        namespace: kargo-demo-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true