apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-billing-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    akuity.io/auto-incident: "sync-app"
spec:
  project: default
  destination:
    name: test
    namespace: default
  source:
    repoURL: https://github.com/Cloud-Hacks/billing-app.git
    path: manifests
    targetRevision: HEAD
