apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr
spec:
  project: default
  source:
    repoURL: 'https://github.com/cloud-hacks/argocd-io'
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: in-cluster
