apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- target:
    kind: Deployment
    name: argocd-application-controller
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-application-controller
      namespace: akuity
    spec:
      template:
        spec:
          containers:
          - name: argocd-application-controller
            env:
            - name: ARGOCD_APPLICATION_CONTROLLER_SERVER_SIDE_DIFF
              value: "true"
              valueFrom: null